#!/bin/sh
#SBATCH --account=cheme
#SBATCH --nodes=1
#SBATCH --tasks-per-node=12
#SBATCH --time=4:20:00
#SBATCH --mem-per-cpu=6gb
#SBATCH --threads-per-core=1
#SBATCH --output=stdout.out
#SBATCH --error=stderr.out

module load intel-parallel-studio/2017
ulimit -s unlimited

date
./mdrun-NVT.sh
date
